# Install script for directory: C:/Users/syoung/Documents/CppTest/cpptest/runtime

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/cpptest")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/objects-Debug/cpptest_lib" TYPE FILE FILES "cpptest.obj" FILES_FROM_DIR "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/cpptest_lib.dir/Debug/")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/objects-Release/cpptest_lib" TYPE FILE FILES "cpptest.obj" FILES_FROM_DIR "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/cpptest_lib.dir/Release/")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/objects-MinSizeRel/cpptest_lib" TYPE FILE FILES "cpptest.obj" FILES_FROM_DIR "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/cpptest_lib.dir/MinSizeRel/")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/objects-RelWithDebInfo/cpptest_lib" TYPE FILE FILES "cpptest.obj" FILES_FROM_DIR "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/cpptest_lib.dir/RelWithDebInfo/")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/Debug/cpptest_shared.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/Release/cpptest_shared.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/MinSizeRel/cpptest_shared.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/RelWithDebInfo/cpptest_shared.lib")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/Debug/cpptest_shared.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/Release/cpptest_shared.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/MinSizeRel/cpptest_shared.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/RelWithDebInfo/cpptest_shared.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/Debug/cpptest_static.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/Release/cpptest_static.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/MinSizeRel/cpptest_static.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/RelWithDebInfo/cpptest_static.lib")
  endif()
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
if(CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_COMPONENT MATCHES "^[a-zA-Z0-9_.+-]+$")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
  else()
    string(MD5 CMAKE_INST_COMP_HASH "${CMAKE_INSTALL_COMPONENT}")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INST_COMP_HASH}.txt")
    unset(CMAKE_INST_COMP_HASH)
  endif()
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "C:/Users/syoung/Documents/CppTest/cpptest/examples/Timer/actions-runner/_work/VSCodeIntegrate/VSCodeIntegrate/cpptest-runtime/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
